version: '3.8'

services:
  api:
    build:
      context: .
    restart: "always"
    volumes:
      #Use the local app folder, but use a named volume for node_modules. This avoids conflicts with the local system.
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo
